// Writes dist/sw.js, the service worker that makes the site installable and usable offline.
// Runs after prerender (see package.json "build").
//
// It precaches the app shell (/) and every built asset: the router renders any page from the
// shell, so the prerendered pages (there for search engines) are not needed offline. Pages are
// fetched network-first, so an online visitor always gets the latest deploy; hashed assets are
// served from the cache. The previous version's cache is kept, so a tab left open across a deploy
// can still load its code-split chunks.
import { createHash } from 'node:crypto';
import { readdirSync, readFileSync, statSync, writeFileSync } from 'node:fs';
import { join, relative } from 'node:path';

const DIST = 'dist';
const walk = (dir) => readdirSync(dir).flatMap((f) => (statSync(join(dir, f)).isDirectory() ? walk(join(dir, f)) : [join(dir, f)]));
const url = (file) => '/' + relative(DIST, file).split('\\').join('/');

const assets = walk(join(DIST, 'assets')).map(url);
const extras = ['/favicon.svg', '/favicon-96.png', '/icon-192.png', '/icon-512.png', '/apple-touch-icon.png', '/site.webmanifest'];
const files = ['/index.html', ...assets, ...extras];
const hash = createHash('sha256');
for (const f of files.sort()) hash.update(f).update(readFileSync(join(DIST, f)));
const version = hash.digest('hex').slice(0, 12);
const precache = ['/', ...assets, ...extras];

const sw = `// Generated by scripts/gen-sw.mjs – do not edit.
const PREFIX = 'pcbplanner-';
const CACHE = PREFIX + '${version}';
const PRECACHE = ${JSON.stringify(precache)};

self.addEventListener('install', (event) => {
  event.waitUntil(caches.open(CACHE).then((c) => c.addAll(PRECACHE)).then(() => self.skipWaiting()));
});

self.addEventListener('activate', (event) => {
  event.waitUntil(
    caches
      .keys()
      .then((keys) => {
        // keep this version and the one before it (caches.keys() is in creation order)
        const ours = keys.filter((k) => k.startsWith(PREFIX) && k !== CACHE);
        return Promise.all(ours.slice(0, -1).map((k) => caches.delete(k)));
      })
      .then(() => self.clients.claim()),
  );
});

self.addEventListener('fetch', (event) => {
  const req = event.request;
  if (req.method !== 'GET') return;
  const url = new URL(req.url);
  // other origins (analytics) and Vercel's own endpoints go straight to the network
  if (url.origin !== self.location.origin || url.pathname.startsWith('/_vercel/')) return;
  if (req.mode === 'navigate') {
    // network first; offline, the app shell renders any page
    event.respondWith(fetch(req).catch(() => caches.match('/', { ignoreVary: true })));
    return;
  }
  // ignoreVary: module scripts and stylesheets are requested with an Origin header the precache
  // requests did not have, and servers may answer with "Vary: Origin"
  event.respondWith(caches.match(req, { ignoreSearch: true, ignoreVary: true }).then((hit) => hit || fetch(req)));
});
`;
writeFileSync(join(DIST, 'sw.js'), sw);
console.log(`service worker: ${precache.length} files, version ${version}`);
