import { lazyPage, type LazyPage } from '../lib/lazyPage';
import { PRESETS } from '../lib/stackups';

export interface ToolDef {
  path: string;
  title: string; // headline on the page and name in tool lists
  seoTitle?: string; // title for search results and link previews, when it differs (under ~50 characters before the site name)
  nav: string;
  group: string;
  summary: string;
  component: LazyPage;
}

/** Colour swatch per group, like layer colours in the PCB editor. */
export const GROUP_COLORS: Record<string, string> = {
  'Signal integrity': '#3d8fe0',
  RF: '#5fb0d8',
  Stackup: '#c9a227',
  Thermal: '#e0645a',
  'Power & conductors': '#d08a3c',
  Electronics: '#6cc28c',
  'Power integrity': '#b07ad8',
  'Power supply': '#e07fb0',
  Components: '#4ab3b3',
  Utilities: '#8a8a8a',
};

export const TOOLS: ToolDef[] = [
  {
    path: '/impedance',
    title: 'Impedance Calculator',
    seoTitle: 'PCB Impedance Calculator: Microstrip & Stripline',
    nav: 'Impedance',
    group: 'Signal integrity',
    summary: 'Single-ended and differential microstrip, coated and embedded microstrip, stripline and coplanar lines, solved with a 2D field solver.',
    component: lazyPage(() => import('./Impedance')),
  },
  {
    path: '/timing',
    title: 'Propagation Delay, εeff & Timing',
    nav: 'Delay & timing',
    group: 'Signal integrity',
    summary: 'Propagation delay, length matching from skew, rise time to bandwidth, critical length and wavelength.',
    component: lazyPage(() => import('./Timing')),
  },
  {
    path: '/termination',
    title: 'Signal Termination Calculator',
    nav: 'Termination',
    group: 'Signal integrity',
    summary: 'Source-series, single-ended load and differential load termination from trace impedance, with E-series values, reflection and resistor stress.',
    component: lazyPage(() => import('./Termination')),
  },
  {
    path: '/trace-loss',
    title: 'Trace Loss (Insertion Loss) Calculator',
    nav: 'Trace loss',
    group: 'Signal integrity',
    summary: 'Insertion loss in dB/in and over the full length: conductor loss with copper roughness and dielectric loss from the field solver, with laminate Dk/Df across frequency.',
    component: lazyPage(() => import('./TraceLoss')),
  },
  {
    path: '/crosstalk',
    title: 'Crosstalk Calculator',
    nav: 'Crosstalk',
    group: 'Signal integrity',
    summary: 'Near- and far-end crosstalk between parallel traces from the field solver, with a sweep over the spacing (3W rule check).',
    component: lazyPage(() => import('./Crosstalk')),
  },
  {
    path: '/differential-via',
    title: 'Differential Via',
    seoTitle: 'Differential Via Impedance Calculator',
    nav: 'Differential via',
    group: 'Signal integrity',
    summary: 'Via-pair differential impedance through the plane clearance from a 2D field solution, antipad sizing for a target, stub resonance and delay.',
    component: lazyPage(() => import('./DiffVia')),
  },
  {
    path: '/via-stitching',
    title: 'Via Stitching & Via Fence Spacing',
    nav: 'Via stitching',
    group: 'Signal integrity',
    summary: 'Stitching and fence via pitch from the wavelength (λ/10, λ/20), via-grid cell resonance, leakage between vias and plane-pair cavity resonances.',
    component: lazyPage(() => import('./ViaStitching')),
  },
  {
    path: '/interface-rules',
    title: 'Interface Design Rules',
    nav: 'Interface rules',
    group: 'Signal integrity',
    summary: 'Impedance, skew, loss budget and length limits of PCIe, USB, Ethernet, HDMI, DDR and other interfaces, applied to a layer of your own stackup with the field solver.',
    component: lazyPage(() => import('./InterfaceRules')),
  },
  {
    path: '/clock-jitter',
    title: 'Phase Noise to Jitter & Jitter Budget',
    seoTitle: 'Phase Noise to Jitter Calculator & Jitter Budget',
    nav: 'Phase noise & jitter',
    group: 'Signal integrity',
    summary: 'RMS phase jitter from an oscillator phase noise curve by exact segment integration, jitter-limited ADC SNR and ENOB, and total jitter at a BER from random and deterministic terms.',
    component: lazyPage(() => import('./ClockJitter')),
  },
  {
    path: '/s-parameter-viewer',
    title: 'S-Parameter Viewer (.s2p, .s4p)',
    seoTitle: 'S2P & S4P Viewer: Mixed-Mode, TDR, Group Delay',
    nav: 'S-parameter viewer',
    group: 'Signal integrity',
    summary: 'Open .s1p to .s16p Touchstone files in the browser: insertion and return loss, phase, group delay, mixed-mode SDD21/SCD21 for 4-ports, TDR impedance and interface loss budgets.',
    component: lazyPage(() => import('./SParameterViewer')),
  },
  {
    path: '/vswr-calculator',
    title: 'VSWR, Return Loss & Mismatch Loss Calculator',
    seoTitle: 'VSWR to Return Loss & Mismatch Loss Calculator',
    nav: 'VSWR & return loss',
    group: 'RF',
    summary: 'Convert between VSWR, |Γ|, return loss, mismatch loss and reflected power, find Γ of a complex load, and bound the mismatch uncertainty and cascaded VSWR of two ports.',
    component: lazyPage(() => import('./Vswr')),
  },
  {
    path: '/coax-impedance',
    title: 'Coaxial Line Impedance Calculator',
    seoTitle: 'Coax Impedance Calculator (incl. Offset Centre)',
    nav: 'Coax impedance',
    group: 'RF',
    summary: 'Characteristic impedance of a coaxial line from D, d and εr, or the diameter for a target Z0, with offset centre conductor, delay, C and L per metre, TE11 cutoff and loss.',
    component: lazyPage(() => import('./CoaxImpedance')),
  },
  {
    path: '/impedance-matching',
    title: 'L-Network Impedance Matching & Smith Chart',
    seoTitle: 'L-Network Impedance Matching Calculator',
    nav: 'L-network matching',
    group: 'RF',
    summary: 'Two-element L-section matching of a complex load: every low-pass and high-pass solution with L and C values, node Q, swept return loss, bandwidth, nearest E-series parts and a Smith chart.',
    component: lazyPage(() => import('./ImpedanceMatching')),
  },
  {
    path: '/quarter-wave-transformer',
    title: 'Quarter-Wave Transformer & Stub Calculator',
    nav: 'Quarter-wave & stubs',
    group: 'RF',
    summary: 'Single and multisection binomial or Chebyshev λ/4 transformers with exact response and bandwidth, open and short stubs, and single-stub matching, with physical lengths and trace widths.',
    component: lazyPage(() => import('./QuarterWave')),
  },
  {
    path: '/stackup-advisor',
    title: 'Stackup Advisor',
    seoTitle: 'PCB Stackup Finder by Thickness & Layer Count',
    nav: 'Stackup advisor',
    group: 'Stackup',
    summary: 'Find stackups by board thickness and layer count, with optional impedance requirements to rank candidates and solve trace widths.',
    component: lazyPage(() => import('./StackupAdvisor')),
  },
  {
    path: '/stackup',
    title: 'Layer Stack Manager',
    nav: 'Layer stack manager',
    group: 'Stackup',
    summary: `${PRESETS.length} fab stackups from 2 to 12 layers, editable, with any signal layer sent to the impedance calculator.`,
    component: lazyPage(() => import('./StackupTool')),
  },
  {
    path: '/pcb-materials',
    title: 'PCB Laminate Materials (Dk / Df)',
    nav: 'Materials (Dk/Df)',
    group: 'Stackup',
    summary: 'Datasheet Dk and Df of FR-4, low-loss and RF laminates (Isola, Panasonic, Rogers, Shengyi…) at any frequency, plus solder masks and copper foil roughness.',
    component: lazyPage(() => import('./Materials')),
  },
  {
    path: '/junction-temperature',
    title: 'Junction Temperature',
    nav: 'Junction temperature',
    group: 'Thermal',
    summary: 'Junction temperature from power and the thermal-resistance chain (θJA or θJC + θCS + θSA), and the maximum power for a Tj limit.',
    component: lazyPage(() => import('./ThermalJunction')),
  },
  {
    path: '/thermal-vias',
    title: 'Thermal Via Array',
    seoTitle: 'PCB Thermal Via Calculator',
    nav: 'Thermal vias',
    group: 'Thermal',
    summary: 'Thermal resistance of a via array under a hot pad, with plugged or filled vias, and the temperature drop through the board.',
    component: lazyPage(() => import('./ThermalVias')),
  },
  {
    path: '/copper-heat-spreading',
    title: 'Copper Area for Heat Spreading',
    nav: 'Copper heat spreading',
    group: 'Thermal',
    summary: 'How much copper a hot part needs: copper-pour thermal resistance by convection and radiation, junction temperature and the smallest pour for a Tj limit.',
    component: lazyPage(() => import('./CopperSpreading')),
  },
  {
    path: '/trace-width',
    title: 'Trace Width, Current & Temperature Rise',
    nav: 'Trace width / current',
    group: 'Power & conductors',
    summary: 'IPC-2221: width for a current, current for a width, or temperature rise of a trace, with resistance, voltage drop and loss.',
    component: lazyPage(() => import('./TraceWidth')),
  },
  {
    path: '/via',
    title: 'Via Calculator',
    seoTitle: 'PCB Via Current & Resistance Calculator',
    nav: 'Via',
    group: 'Power & conductors',
    summary: 'Via current capacity, resistance, thermal resistance, capacitance, inductance and rise-time impact.',
    component: lazyPage(() => import('./Via')),
  },
  {
    path: '/skin-effect',
    title: 'Skin Effect & AC Resistance',
    nav: 'Skin effect',
    group: 'Power & conductors',
    summary: 'Skin depth in copper and the AC resistance of a trace across frequency.',
    component: lazyPage(() => import('./SkinEffect')),
  },
  {
    path: '/fusing',
    title: 'Fusing Current',
    seoTitle: 'PCB Trace Fusing Current Calculator',
    nav: 'Fusing current',
    group: 'Power & conductors',
    summary: 'Current that melts a trace in a given time (Onderdonk), for fault and surge analysis.',
    component: lazyPage(() => import('./Fusing')),
  },
  {
    path: '/wire-gauge',
    title: 'Wire Gauge & Voltage Drop',
    nav: 'Wire gauge / drop',
    group: 'Power & conductors',
    summary: 'AWG diameter, area and resistance, cable voltage drop and loss, the smallest gauge for a drop limit, and Preece fusing current.',
    component: lazyPage(() => import('./WireGauge')),
  },
  {
    path: '/conductor-spacing',
    title: 'Conductor Spacing (IPC-2221)',
    nav: 'Conductor spacing',
    group: 'Power & conductors',
    summary: 'Minimum electrical clearance between conductors from IPC-2221 Table 6-1: internal, external, coated, high altitude, assemblies.',
    component: lazyPage(() => import('./ConductorSpacing')),
  },
  {
    path: '/creepage-clearance',
    title: 'Creepage & Clearance (IEC 60664-1)',
    nav: 'Creepage & clearance',
    group: 'Power & conductors',
    summary: 'Minimum clearance and creepage per IEC 60664-1: impulse voltage from mains and overvoltage category, pollution degree, CTI material group, reinforced insulation, altitude.',
    component: lazyPage(() => import('./CreepageClearance')),
  },
  {
    path: '/pdn',
    title: 'PDN Impedance Calculator',
    nav: 'PDN',
    group: 'Power integrity',
    summary: 'Target impedance, plane-pair capacitance, decoupling-capacitor resonance and the number of capacitors needed, with a log-log |Z|(f) plot.',
    component: lazyPage(() => import('./Pdn')),
  },
  {
    path: '/power-tree',
    title: 'Power Tree Planner',
    nav: 'Power tree',
    group: 'Power supply',
    summary: 'Budget source and regulator currents across cascaded rails and loads, estimate losses, check ratings and record power-up dependencies.',
    component: lazyPage(() => import('./PowerTree')),
  },
  {
    path: '/buck-converter',
    title: 'Buck Converter Calculator',
    nav: 'Buck converter',
    group: 'Power supply',
    summary: 'Buck power-stage sizing with conduction-mode checks, real inductor and capacitor ratings, IC timing limits and current waveforms across the input range.',
    component: lazyPage(() => import('./Buck')),
  },
  {
    path: '/boost-converter',
    title: 'Boost Converter Calculator',
    nav: 'Boost converter',
    group: 'Power supply',
    summary: 'Boost power-stage sizing with conduction-mode checks, real inductor and capacitor ratings, IC timing limits and current waveforms across the input range.',
    component: lazyPage(() => import('./Boost')),
  },
  {
    path: '/ldo',
    title: 'LDO Regulator Power Dissipation',
    nav: 'LDO dissipation',
    group: 'Power supply',
    summary: 'Linear regulator dissipation, junction temperature, efficiency and dropout headroom, with the maximum load for a Tj limit.',
    component: lazyPage(() => import('./Ldo')),
  },
  {
    path: '/feedback-divider',
    title: 'Feedback Resistor Divider',
    nav: 'Feedback divider',
    group: 'Power supply',
    summary: 'Standard-value R1/R2 for adjustable regulators: the best E12/E24/E96 pairs, output error, FB bias current and worst case with tolerance.',
    component: lazyPage(() => import('./FeedbackDivider')),
  },
  {
    path: '/planar-inductor',
    title: 'Planar Spiral Inductor',
    nav: 'Spiral inductor',
    group: 'Components',
    summary: 'Inductance of square, hexagonal, octagonal and circular PCB spirals (modified Wheeler and current-sheet models), with DC resistance and Q.',
    component: lazyPage(() => import('./PlanarInductor')),
  },
  {
    path: '/padstack',
    title: 'Through-Hole Padstack Calculator',
    nav: 'Padstack',
    group: 'Components',
    summary: 'Plated through-hole sizing per IPC-7251 / IPC-2221 / IPC-2222: hole, outer and inner pads, antipad, thermal relief and annular ring for levels A/B/C.',
    component: lazyPage(() => import('./Padstack')),
  },
  {
    path: '/smd-land-pattern',
    title: 'Two-Terminal SMD Land Pattern Calculator',
    seoTitle: 'SMD Resistor & Capacitor Footprint Calculator',
    nav: 'SMD land pattern',
    group: 'Components',
    summary: 'Size the two copper pads, pitch, courtyard and solder-mask openings for a chip resistor or MLCC from the exact part dimensions and process tolerances.',
    component: lazyPage(() => import('./SmdLand')),
  },
  {
    path: '/bga-land',
    title: 'BGA Land Pattern',
    nav: 'BGA land',
    group: 'Components',
    summary: 'IPC-7351 land diameter for collapsing and non-collapsing BGA balls, with tolerance and courtyard, and escape-routing capacity between lands.',
    component: lazyPage(() => import('./BgaLand')),
  },
  {
    path: '/resistor-color-code',
    title: 'Resistor Color Code Calculator',
    nav: 'Resistor color code',
    group: 'Components',
    summary: 'Value, tolerance and temperature coefficient of 4-, 5- and 6-band resistors from their colours (IEC 60062), and the bands for any value.',
    component: lazyPage(() => import('./ResistorColorCode')),
  },
  {
    path: '/smd-resistor-code',
    title: 'SMD Resistor Code Calculator',
    nav: 'SMD resistor code',
    group: 'Components',
    summary: 'Decode 3-digit, 4-digit and EIA-96 SMD resistor markings and R/m decimal notation, and find the code for any value.',
    component: lazyPage(() => import('./SmdResistorCode')),
  },
  {
    path: '/capacitor-code',
    title: 'Capacitor Code Calculator',
    nav: 'Capacitor code',
    group: 'Components',
    summary: 'Decode capacitor markings such as 104K and 2A473J: value, tolerance letter, voltage code, and dielectric codes such as X7R and C0G.',
    component: lazyPage(() => import('./CapacitorCode')),
  },
  {
    path: '/ohms-law',
    title: "Ohm's Law & Power",
    nav: "Ohm's law",
    group: 'Electronics',
    summary: 'Enter any two of voltage, current, resistance and power to get the other two.',
    component: lazyPage(() => import('./OhmsLaw')),
  },
  {
    path: '/reactance',
    title: 'Reactance & LC Resonance',
    nav: 'Reactance & resonance',
    group: 'Electronics',
    summary: 'XL and XC at a frequency, LC resonance, the L or C for a target frequency, and series/parallel LC impedance with Q.',
    component: lazyPage(() => import('./Reactance')),
  },
  {
    path: '/rc-filter',
    title: 'RC Low-Pass & High-Pass Filter Calculator',
    nav: 'RC filters',
    group: 'Electronics',
    summary: 'Passive RC low-pass and high-pass filters with source/load resistance, standard component selection, tolerance bounds and interactive gain and phase plots.',
    component: lazyPage(() => import('./RcFilter')),
  },
  {
    path: '/active-filter',
    title: 'Active Filter Designer',
    seoTitle: 'Sallen-Key & MFB Active Filter Calculator',
    nav: 'Active filters',
    group: 'Electronics',
    summary: 'Sallen-Key and MFB low-pass and high-pass filters to 8th order (Butterworth, Bessel, Chebyshev): component values, standard-value response, and op amp GBW and slew-rate requirements.',
    component: lazyPage(() => import('./ActiveFilter')),
  },
  {
    path: '/op-amp-gain',
    title: 'Op-Amp Gain Calculator',
    seoTitle: 'Op-Amp Gain, Bandwidth, Offset & Noise Calculator',
    nav: 'Op-amp gain',
    group: 'Electronics',
    summary: 'Inverting, non-inverting, difference and summing stages: noise gain, bandwidth, output swing, DC offset, noise and resistor tolerance, with standard-value pairs for a target gain.',
    component: lazyPage(() => import('./OpAmpGain')),
  },
  {
    path: '/crystal',
    title: 'Crystal Load Capacitors & PPM Budget',
    seoTitle: 'Crystal Load Capacitor & PPM Budget Calculator',
    nav: 'Crystal & ppm',
    group: 'Electronics',
    summary: 'Crystal load capacitors with the nearest E12/E24 values and the pulling they cause, a ppm frequency budget checked against USB, Ethernet, PCIe and SATA clock tolerances, and ppm ↔ frequency error and drift.',
    component: lazyPage(() => import('./Crystal')),
  },
  {
    path: '/555-timer',
    title: '555 Timer Calculator',
    nav: '555 timer',
    group: 'Electronics',
    summary: 'Astable frequency and duty cycle, resistor values for a target frequency, and monostable pulse width, from the TI NE555 equations.',
    component: lazyPage(() => import('./Timer555')),
  },
  {
    path: '/i2c-pullup',
    title: 'I²C Pull-up Calculator',
    nav: 'I²C pull-up',
    group: 'Electronics',
    summary: 'Pull-up resistor range for Standard, Fast and Fast-mode Plus I²C from bus capacitance, rise time and device sink current.',
    component: lazyPage(() => import('./I2cPullup')),
  },
  {
    path: '/logic-levels',
    title: 'Logic-Level Compatibility Checker',
    nav: 'Logic levels',
    group: 'Electronics',
    summary: 'Check worst-case VOH/VOL against VIH/VIL, static noise margins and receiver input-voltage limits.',
    component: lazyPage(() => import('./LogicLevels')),
  },
  {
    path: '/comparator-hysteresis',
    title: 'Comparator Hysteresis Calculator',
    seoTitle: 'Comparator Hysteresis & Schmitt Trigger Calculator',
    nav: 'Comparator hysteresis',
    group: 'Electronics',
    summary: 'Inverting and non-inverting switching thresholds: design reference and feedback resistors, choose standard values and check resistor, offset and reference uncertainty.',
    component: lazyPage(() => import('./ComparatorHysteresis')),
  },
  {
    path: '/adc-input',
    title: 'ADC Input Settling Checker',
    nav: 'ADC input',
    group: 'Electronics',
    seoTitle: 'ADC Input Settling & Accuracy Budget Calculator',
    summary: 'SAR ADC source and RC filter settling during acquisition, filter-node recovery, and an optional DC accuracy budget for offset, gain, reference, INL and quantisation.',
    component: lazyPage(() => import('./AdcInput')),
  },
  {
    path: '/ntc-thermistor',
    title: 'NTC Thermistor Calculator',
    seoTitle: 'NTC Thermistor Calculator: Beta, Steinhart–Hart & ADC',
    nav: 'NTC thermistor',
    group: 'Electronics',
    summary: 'Beta and Steinhart–Hart models with coefficient fitting, a thermistor divider into an ADC with °C/LSB, series-resistor choice, self-heating, tolerance error and a CSV or C lookup table.',
    component: lazyPage(() => import('./NtcThermistor')),
  },
  {
    path: '/current-sense-shunt',
    title: 'Current-Sense Shunt Selector',
    nav: 'Current-sense shunt',
    group: 'Electronics',
    summary: 'Select a shunt from current range and voltage-drop budget, with power, tolerance, TCR and amplifier-offset checks.',
    component: lazyPage(() => import('./CurrentShunt')),
  },
  {
    path: '/resistors',
    title: 'Resistor Tools',
    seoTitle: 'Voltage Divider & LED Resistor Calculator',
    nav: 'Resistor tools',
    group: 'Electronics',
    summary: 'Voltage divider with best E12/E24/E96 pairs, LED series resistor with power rating, and series/parallel R, C and L.',
    component: lazyPage(() => import('./Resistors')),
  },
  {
    path: '/attenuator',
    title: 'Attenuator Pads',
    seoTitle: 'Pi & T Attenuator Calculator',
    nav: 'Attenuator pads',
    group: 'Electronics',
    summary: 'Matched Pi, T and bridged-T pads with the nearest standard values, their actual loss and return loss, and resistor power.',
    component: lazyPage(() => import('./Attenuator')),
  },
  {
    path: '/projects',
    title: 'Projects',
    nav: 'Projects',
    group: 'Utilities',
    summary: 'Save the inputs of every calculator for a board under one name, reopen them later, and export or import them as a project file.',
    component: lazyPage(() => import('./Projects')),
  },
  {
    path: '/units',
    title: 'Unit Converter',
    nav: 'Unit converter',
    group: 'Utilities',
    summary: 'Length, copper weight, temperature, power (dBm/W/V) and frequency/wavelength.',
    component: lazyPage(() => import('./Units')),
  },
  {
    path: '/reference-charts',
    title: 'Reference Charts',
    seoTitle: 'Drill Size, Tap Drill & AWG Charts',
    nav: 'Reference charts',
    group: 'Utilities',
    summary: 'Drill sizes (number, letter, fractional, metric), ISO metric and Unified threads with tap and clearance drills, and the AWG wire table.',
    component: lazyPage(() => import('./ReferenceCharts')),
  },
];

/** Tools in other groups (or not obviously related) that a tool page links to under "Related tools". */
export const RELATED: Record<string, string[]> = {
  '/vswr-calculator': ['/attenuator', '/impedance-matching', '/coax-impedance', '/s-parameter-viewer'],
  '/coax-impedance': ['/vswr-calculator', '/timing', '/skin-effect', '/impedance'],
  '/impedance-matching': ['/quarter-wave-transformer', '/vswr-calculator', '/reactance', '/s-parameter-viewer'],
  '/quarter-wave-transformer': ['/impedance-matching', '/impedance', '/timing', '/differential-via'],
  '/s-parameter-viewer': ['/vswr-calculator', '/trace-loss', '/interface-rules'],
  '/attenuator': ['/vswr-calculator', '/impedance-matching'],
  '/reactance': ['/impedance-matching', '/active-filter'],
  '/rc-filter': ['/active-filter', '/adc-input'],
  '/active-filter': ['/rc-filter', '/op-amp-gain', '/adc-input'],
  '/op-amp-gain': ['/active-filter', '/resistors', '/current-sense-shunt', '/adc-input'],
  '/ntc-thermistor': ['/adc-input', '/resistors', '/rc-filter'],
  '/adc-input': ['/ntc-thermistor', '/active-filter', '/op-amp-gain', '/clock-jitter'],
  '/comparator-hysteresis': ['/logic-levels', '/resistors', '/ntc-thermistor', '/op-amp-gain'],
  '/logic-levels': ['/comparator-hysteresis', '/i2c-pullup'],
  '/clock-jitter': ['/crystal', '/adc-input', '/interface-rules'],
  '/crystal': ['/clock-jitter'],
  '/current-sense-shunt': ['/op-amp-gain'],
  '/resistors': ['/op-amp-gain', '/ntc-thermistor'],
};

export const relatedTools = (p: string) => (RELATED[p] ?? []).map(toolByPath).filter((t): t is ToolDef => !!t);

export const GROUPS = [...new Set(TOOLS.map((t) => t.group))];
export const toolByPath = (p: string) => TOOLS.find((t) => t.path === p);
