import { lazy, type ComponentType, type LazyExoticComponent } from 'react';
import { PRESETS } from '../lib/stackups';

export interface ToolDef {
  path: string;
  title: string;
  nav: string;
  group: string;
  summary: string;
  component: LazyExoticComponent<ComponentType>;
}

/** Colour swatch per group, like layer colours in the PCB editor. */
export const GROUP_COLORS: Record<string, string> = {
  'Signal integrity': '#3d8fe0',
  Stackup: '#c9a227',
  Thermal: '#e0645a',
  'Power & conductors': '#d08a3c',
  Electronics: '#6cc28c',
  'Power integrity': '#b07ad8',
  'Power supply': '#e07fb0',
  Components: '#4ab3b3',
  Utilities: '#8a8a8a',
};

export const TOOLS: ToolDef[] = [
  {
    path: '/impedance',
    title: 'Impedance Calculator',
    nav: 'Impedance',
    group: 'Signal integrity',
    summary: 'Single-ended and differential microstrip, coated and embedded microstrip, stripline and coplanar lines, solved with a 2D field solver.',
    component: lazy(() => import('./Impedance')),
  },
  {
    path: '/timing',
    title: 'Propagation Delay, εeff & Timing',
    nav: 'Delay & timing',
    group: 'Signal integrity',
    summary: 'Propagation delay, length matching from skew, rise time to bandwidth, critical length and wavelength.',
    component: lazy(() => import('./Timing')),
  },
  {
    path: '/termination',
    title: 'Signal Termination Calculator',
    nav: 'Termination',
    group: 'Signal integrity',
    summary: 'Source-series, single-ended load and differential load termination from trace impedance, with E-series values, reflection and resistor stress.',
    component: lazy(() => import('./Termination')),
  },
  {
    path: '/trace-loss',
    title: 'Trace Loss (Insertion Loss) Calculator',
    nav: 'Trace loss',
    group: 'Signal integrity',
    summary: 'Insertion loss in dB/in and over the full length: conductor loss with copper roughness and dielectric loss from the field solver, with laminate Dk/Df across frequency.',
    component: lazy(() => import('./TraceLoss')),
  },
  {
    path: '/crosstalk',
    title: 'Crosstalk Calculator',
    nav: 'Crosstalk',
    group: 'Signal integrity',
    summary: 'Near- and far-end crosstalk between parallel traces from the field solver, with a sweep over the spacing (3W rule check).',
    component: lazy(() => import('./Crosstalk')),
  },
  {
    path: '/differential-via',
    title: 'Differential Via',
    nav: 'Differential via',
    group: 'Signal integrity',
    summary: 'Via-pair differential impedance through the plane clearance from a 2D field solution, antipad sizing for a target, stub resonance and delay.',
    component: lazy(() => import('./DiffVia')),
  },
  {
    path: '/via-stitching',
    title: 'Via Stitching & Via Fence Spacing',
    nav: 'Via stitching',
    group: 'Signal integrity',
    summary: 'Stitching and fence via pitch from the wavelength (λ/10, λ/20), via-grid cell resonance, leakage between vias and plane-pair cavity resonances.',
    component: lazy(() => import('./ViaStitching')),
  },
  {
    path: '/interface-rules',
    title: 'Interface Design Rules',
    nav: 'Interface rules',
    group: 'Signal integrity',
    summary: 'Impedance, skew, loss budget and length limits of PCIe, USB, Ethernet, HDMI, DDR and other interfaces, applied to a layer of your own stackup with the field solver.',
    component: lazy(() => import('./InterfaceRules')),
  },
  {
    path: '/stackup-advisor',
    title: 'Stackup Advisor',
    nav: 'Stackup advisor',
    group: 'Stackup',
    summary: 'Find stackups by board thickness and layer count, with optional impedance requirements to rank candidates and solve trace widths.',
    component: lazy(() => import('./StackupAdvisor')),
  },
  {
    path: '/stackup',
    title: 'Layer Stack Manager',
    nav: 'Layer stack manager',
    group: 'Stackup',
    summary: `${PRESETS.length} fab stackups from 2 to 12 layers, editable, with any signal layer sent to the impedance calculator.`,
    component: lazy(() => import('./StackupTool')),
  },
  {
    path: '/pcb-materials',
    title: 'PCB Laminate Materials (Dk / Df)',
    nav: 'Materials (Dk/Df)',
    group: 'Stackup',
    summary: 'Datasheet Dk and Df of FR-4, low-loss and RF laminates (Isola, Panasonic, Rogers, Shengyi…) at any frequency, plus solder masks and copper foil roughness.',
    component: lazy(() => import('./Materials')),
  },
  {
    path: '/junction-temperature',
    title: 'Junction Temperature',
    nav: 'Junction temperature',
    group: 'Thermal',
    summary: 'Junction temperature from power and the thermal-resistance chain (θJA or θJC + θCS + θSA), and the maximum power for a Tj limit.',
    component: lazy(() => import('./ThermalJunction')),
  },
  {
    path: '/thermal-vias',
    title: 'Thermal Via Array',
    nav: 'Thermal vias',
    group: 'Thermal',
    summary: 'Thermal resistance of a via array under a hot pad, with plugged or filled vias, and the temperature drop through the board.',
    component: lazy(() => import('./ThermalVias')),
  },
  {
    path: '/copper-heat-spreading',
    title: 'Copper Area for Heat Spreading',
    nav: 'Copper heat spreading',
    group: 'Thermal',
    summary: 'How much copper a hot part needs: copper-pour thermal resistance by convection and radiation, junction temperature and the smallest pour for a Tj limit.',
    component: lazy(() => import('./CopperSpreading')),
  },
  {
    path: '/trace-width',
    title: 'Trace Width, Current & Temperature Rise',
    nav: 'Trace width / current',
    group: 'Power & conductors',
    summary: 'IPC-2221: width for a current, current for a width, or temperature rise of a trace, with resistance, voltage drop and loss.',
    component: lazy(() => import('./TraceWidth')),
  },
  {
    path: '/via',
    title: 'Via Calculator',
    nav: 'Via',
    group: 'Power & conductors',
    summary: 'Via current capacity, resistance, thermal resistance, capacitance, inductance and rise-time impact.',
    component: lazy(() => import('./Via')),
  },
  {
    path: '/skin-effect',
    title: 'Skin Effect & AC Resistance',
    nav: 'Skin effect',
    group: 'Power & conductors',
    summary: 'Skin depth in copper and the AC resistance of a trace across frequency.',
    component: lazy(() => import('./SkinEffect')),
  },
  {
    path: '/fusing',
    title: 'Fusing Current',
    nav: 'Fusing current',
    group: 'Power & conductors',
    summary: 'Current that melts a trace in a given time (Onderdonk), for fault and surge analysis.',
    component: lazy(() => import('./Fusing')),
  },
  {
    path: '/wire-gauge',
    title: 'Wire Gauge & Voltage Drop',
    nav: 'Wire gauge / drop',
    group: 'Power & conductors',
    summary: 'AWG diameter, area and resistance, cable voltage drop and loss, the smallest gauge for a drop limit, and Preece fusing current.',
    component: lazy(() => import('./WireGauge')),
  },
  {
    path: '/conductor-spacing',
    title: 'Conductor Spacing (IPC-2221)',
    nav: 'Conductor spacing',
    group: 'Power & conductors',
    summary: 'Minimum electrical clearance between conductors from IPC-2221 Table 6-1: internal, external, coated, high altitude, assemblies.',
    component: lazy(() => import('./ConductorSpacing')),
  },
  {
    path: '/creepage-clearance',
    title: 'Creepage & Clearance (IEC 60664-1)',
    nav: 'Creepage & clearance',
    group: 'Power & conductors',
    summary: 'Minimum clearance and creepage per IEC 60664-1: impulse voltage from mains and overvoltage category, pollution degree, CTI material group, reinforced insulation, altitude.',
    component: lazy(() => import('./CreepageClearance')),
  },
  {
    path: '/pdn',
    title: 'PDN Impedance Calculator',
    nav: 'PDN',
    group: 'Power integrity',
    summary: 'Target impedance, plane-pair capacitance, decoupling-capacitor resonance and the number of capacitors needed, with a log-log |Z|(f) plot.',
    component: lazy(() => import('./Pdn')),
  },
  {
    path: '/power-tree',
    title: 'Power Tree Planner',
    nav: 'Power tree',
    group: 'Power supply',
    summary: 'Budget source and regulator currents across cascaded rails and loads, estimate losses, check ratings and record power-up dependencies.',
    component: lazy(() => import('./PowerTree')),
  },
  {
    path: '/buck-converter',
    title: 'Buck Converter Calculator',
    nav: 'Buck converter',
    group: 'Power supply',
    summary: 'Buck power-stage sizing with conduction-mode checks, real inductor and capacitor ratings, IC timing limits and current waveforms across the input range.',
    component: lazy(() => import('./Buck')),
  },
  {
    path: '/boost-converter',
    title: 'Boost Converter Calculator',
    nav: 'Boost converter',
    group: 'Power supply',
    summary: 'Boost power-stage sizing with conduction-mode checks, real inductor and capacitor ratings, IC timing limits and current waveforms across the input range.',
    component: lazy(() => import('./Boost')),
  },
  {
    path: '/ldo',
    title: 'LDO Regulator Power Dissipation',
    nav: 'LDO dissipation',
    group: 'Power supply',
    summary: 'Linear regulator dissipation, junction temperature, efficiency and dropout headroom, with the maximum load for a Tj limit.',
    component: lazy(() => import('./Ldo')),
  },
  {
    path: '/feedback-divider',
    title: 'Feedback Resistor Divider',
    nav: 'Feedback divider',
    group: 'Power supply',
    summary: 'Standard-value R1/R2 for adjustable regulators: the best E12/E24/E96 pairs, output error, FB bias current and worst case with tolerance.',
    component: lazy(() => import('./FeedbackDivider')),
  },
  {
    path: '/planar-inductor',
    title: 'Planar Spiral Inductor',
    nav: 'Spiral inductor',
    group: 'Components',
    summary: 'Inductance of square, hexagonal, octagonal and circular PCB spirals (modified Wheeler and current-sheet models), with DC resistance and Q.',
    component: lazy(() => import('./PlanarInductor')),
  },
  {
    path: '/padstack',
    title: 'Through-Hole Padstack Calculator',
    nav: 'Padstack',
    group: 'Components',
    summary: 'Plated through-hole sizing per IPC-7251 / IPC-2221 / IPC-2222: hole, outer and inner pads, antipad, thermal relief and annular ring for levels A/B/C.',
    component: lazy(() => import('./Padstack')),
  },
  {
    path: '/bga-land',
    title: 'BGA Land Pattern',
    nav: 'BGA land',
    group: 'Components',
    summary: 'IPC-7351 land diameter for collapsing and non-collapsing BGA balls, with tolerance and courtyard, and escape-routing capacity between lands.',
    component: lazy(() => import('./BgaLand')),
  },
  {
    path: '/ohms-law',
    title: "Ohm's Law & Power",
    nav: "Ohm's law",
    group: 'Electronics',
    summary: 'Enter any two of voltage, current, resistance and power to get the other two.',
    component: lazy(() => import('./OhmsLaw')),
  },
  {
    path: '/reactance',
    title: 'Reactance & LC Resonance',
    nav: 'Reactance & resonance',
    group: 'Electronics',
    summary: 'XL and XC at a frequency, LC resonance, the L or C for a target frequency, and series/parallel LC impedance with Q.',
    component: lazy(() => import('./Reactance')),
  },
  {
    path: '/rc-filter',
    title: 'RC Low-Pass & High-Pass Filter Calculator',
    nav: 'RC filters',
    group: 'Electronics',
    summary: 'Passive RC low-pass and high-pass filters with source/load resistance, standard component selection, tolerance bounds and interactive gain and phase plots.',
    component: lazy(() => import('./RcFilter')),
  },
  {
    path: '/crystal',
    title: 'Crystal Load Capacitors & PPM',
    nav: 'Crystal & ppm',
    group: 'Electronics',
    summary: 'Crystal load capacitors with the nearest E12/E24 values and resulting CL, plus frequency error ↔ ppm and clock drift.',
    component: lazy(() => import('./Crystal')),
  },
  {
    path: '/i2c-pullup',
    title: 'I²C Pull-up Calculator',
    nav: 'I²C pull-up',
    group: 'Electronics',
    summary: 'Pull-up resistor range for Standard, Fast and Fast-mode Plus I²C from bus capacitance, rise time and device sink current.',
    component: lazy(() => import('./I2cPullup')),
  },
  {
    path: '/logic-levels',
    title: 'Logic-Level Compatibility Checker',
    nav: 'Logic levels',
    group: 'Electronics',
    summary: 'Check worst-case VOH/VOL against VIH/VIL, static noise margins and receiver input-voltage limits.',
    component: lazy(() => import('./LogicLevels')),
  },
  {
    path: '/adc-input',
    title: 'ADC Input Settling Checker',
    nav: 'ADC input',
    group: 'Electronics',
    summary: 'Check source and RC filter settling into a SAR ADC sample capacitor during acquisition, with an optional filter-node recovery check.',
    component: lazy(() => import('./AdcInput')),
  },
  {
    path: '/current-sense-shunt',
    title: 'Current-Sense Shunt Selector',
    nav: 'Current-sense shunt',
    group: 'Electronics',
    summary: 'Select a shunt from current range and voltage-drop budget, with power, tolerance, TCR and amplifier-offset checks.',
    component: lazy(() => import('./CurrentShunt')),
  },
  {
    path: '/resistors',
    title: 'Resistor Tools',
    nav: 'Resistor tools',
    group: 'Electronics',
    summary: 'Voltage divider with best E12/E24/E96 pairs, LED series resistor with power rating, and series/parallel R, C and L.',
    component: lazy(() => import('./Resistors')),
  },
  {
    path: '/attenuator',
    title: 'Attenuator Pads',
    nav: 'Attenuator pads',
    group: 'Electronics',
    summary: 'Matched Pi, T and bridged-T pads with the nearest standard values, their actual loss and return loss, and resistor power.',
    component: lazy(() => import('./Attenuator')),
  },
  {
    path: '/projects',
    title: 'Projects',
    nav: 'Projects',
    group: 'Utilities',
    summary: 'Save the inputs of every calculator for a board under one name, reopen them later, and export or import them as a project file.',
    component: lazy(() => import('./Projects')),
  },
  {
    path: '/units',
    title: 'Unit Converter',
    nav: 'Unit converter',
    group: 'Utilities',
    summary: 'Length, copper weight, temperature, power (dBm/W/V) and frequency/wavelength.',
    component: lazy(() => import('./Units')),
  },
  {
    path: '/reference-charts',
    title: 'Reference Charts',
    nav: 'Reference charts',
    group: 'Utilities',
    summary: 'Drill sizes (number, letter, fractional, metric), ISO metric and Unified threads with tap and clearance drills, and the AWG wire table.',
    component: lazy(() => import('./ReferenceCharts')),
  },
];

export const GROUPS = [...new Set(TOOLS.map((t) => t.group))];
export const toolByPath = (p: string) => TOOLS.find((t) => t.path === p);
